/* 
** Tempo, (C) 1995, Irisa
** Version: $Revision: 1.2 $ 
** Date: %D%
** Author: Nic Volanski
*/
//
// Abstract Syntax Tree for an expression
// (without annotations)
//
#ifndef _ast_H_
#define _ast_H_

typedef char *identifier;

typedef char *exp;  // the ML representation
typedef char *stmt;
typedef char *ML_ast; // the ML representation
typedef char *ML_ctx; // an ML_ast pattern with a %s hole
#endif _ast_H_
